using System.Runtime.InteropServices;
using System.Text;

namespace PCModeSwitcher.Services;

internal static partial class LocalizationStrings
{
    private const uint SimplifiedChineseMapFlag = 0x02000000;

    private static readonly (string From, string To)[] MainlandChineseVocabulary =
    [
        ("应用程式", "应用程序"),
        ("程式", "程序"),
        ("设定", "设置"),
        ("预设", "默认"),
        ("目前", "当前"),
        ("使用者", "用户"),
        ("资料夹", "文件夹"),
        ("档案", "文件"),
        ("快速键", "快捷键"),
        ("音讯", "音频"),
        ("音效", "声音"),
        ("萤幕", "屏幕"),
        ("重新整理频率", "刷新率"),
        ("电源计画", "电源计划"),
        ("储存", "保存"),
        ("载入", "加载"),
        ("检视", "查看"),
        ("略过", "跳过"),
        ("资讯", "信息")
    ];

    // Esperanto is deliberately an opt-in, experimental translation. Frequently used UI is
    // translated here; uncommon diagnostics and service errors retain the English fallback.
    private static readonly (string Key, string Value)[] EsperantoUi =
    [
        ("Language.System", "Defaŭlta (montra lingvo de Windows)"),
        ("Language.Japanese", "Japana"),
        ("Language.English", "Angla"),
        ("Language.SimplifiedChinese", "Simpligita ĉina"),
        ("Language.TraditionalChinese", "Tradicia ĉina"),
        ("Language.Spanish", "Hispana"),
        ("Language.Arabic", "Araba"),
        ("Language.Hindi", "Hindia"),
        ("Language.Esperanto", "Esperanto (eksperimenta)"),
        ("Common.Apply", "Apliki"),
        ("Common.Edit", "Redakti"),
        ("Common.Cancel", "Nuligi"),
        ("Common.Save", "Konservi"),
        ("Common.Close", "Fermi"),
        ("Common.Restore", "Restarigi"),
        ("Common.Duplicate", "Duobligi"),
        ("Common.Hide", "Kaŝi"),
        ("Common.Clear", "Forigi"),
        ("Common.DeleteSelection", "Forigi elektitajn"),
        ("Common.None", "Neniam"),
        ("Common.NoChange", "Ne ŝanĝi"),
        ("Common.Unknown", "Nekonata"),
        ("Main.Menu.Mode", "Reĝimo"),
        ("Main.Menu.RestorePreModeState", "Restarigi la staton antaŭ apliko de la reĝimo"),
        ("Main.Menu.New", "Nova..."),
        ("Main.Menu.Import", "Importi reĝimajn agordojn..."),
        ("Main.Menu.Export", "Eksporti reĝimajn agordojn..."),
        ("Main.Menu.Settings", "Agordoj"),
        ("Main.Menu.AppSettings", "Agordoj de la aplikaĵo..."),
        ("Main.Menu.Diagnostics", "Diagnozo..."),
        ("Main.Menu.Help", "Helpo"),
        ("Update.CheckMenu", "Kontroli ĝisdatigojn..."),
        ("Main.Menu.Support", "Subteni la evoluadon..."),
        ("Main.Menu.About", "Pri PC Mode Switcher"),
        ("Main.Tagline", "Ŝanĝu la komputilajn agordojn per unu klako laŭ via uzo."),
        ("Main.RestorePrompt", "Ĉu restarigi la antaŭajn agordojn?"),
        ("Main.CurrentMode", "NUNA REĜIMO"),
        ("Main.Drag", "↔ Trenu por reordigi"),
        ("Main.DragTip", "Trenu maldekstren aŭ dekstren por ŝanĝi la ordon"),
        ("Main.DisplayOff", "MALŜALTI EKRANON"),
        ("Main.Sleep", "DORMETO"),
        ("Main.PowerMode", "ENERGIA REĜIMO"),
        ("Main.Microphone", "MIKROFONO"),
        ("Main.Review", "Kontroli agojn"),
        ("Main.HideTip", "Kaŝas ĉi tiun reĝimon sen forigi ĝiajn agordojn"),
        ("Update.Available", "Nova versio {0} disponeblas"),
        ("Update.ViewRelease", "Vidi ŝanĝojn"),
        ("Update.Dismiss", "Fermi sciigon pri ĉi tiu versio"),
        ("Update.Title", "Kontroli ĝisdatigojn"),
        ("Update.ManualAvailable", "Nova versio {0} disponeblas.\n\nĈu malfermi la ŝanĝojn en GitHub?"),
        ("Update.UpToDate", "{0} estas la plej nova versio."),
        ("Update.CheckFailed", "Ne eblis kontroli ĝisdatigojn. Provu denove poste."),
        ("Update.NoReleasePage", "Ne eblis malfermi la paĝon pri la ĝisdatigo."),
        ("Update.NotificationTitle", "Ĝisdatigo de PC Mode Switcher"),
        ("Settings.Title", "Agordoj de la aplikaĵo"),
        ("Settings.Description", "Agordu la lingvon, videblajn reĝimojn, startigon, fermbutonon kaj fulmoklavojn."),
        ("Settings.Language", "Montra lingvo"),
        ("Settings.LanguageDescription", "Defaŭlte estas uzata la montra lingvo de Windows. Vi ankaŭ povas elekti la japanan, anglan, simpligitan aŭ tradician ĉinan, hispanan, araban, hindian aŭ eksperimentan Esperanton."),
        ("Settings.Updates", "Ĝisdatigoj"),
        ("Settings.CheckForUpdatesAutomatically", "Aŭtomate kontroli novajn versiojn"),
        ("Settings.UpdateDescription", "Kontrolas 30 sekundojn post startigo kaj poste ĉiujn 24 horojn. Sciigas nur kiam nova versio disponeblas."),
        ("Settings.MicrophoneFeature", "Mikrofonaj regiloj"),
        ("Settings.EnableMicrophone", "Ebligi montradon kaj regadon de la mikrofono"),
        ("Settings.MicrophoneDescription", "Kiam malŝaltita, la mikrofonaj opcioj estas kaŝitaj kaj reĝimoj ne ŝanĝas la mikrofonon. Konservitaj agordoj restas."),
        ("Settings.Startup", "Startigo ĉe ensaluto en Windows"),
        ("Settings.StartWithWindows", "Aŭtomate startigi kiam mi ensalutas en Windows"),
        ("Settings.StartupDescription", "Validas nur por la nuna uzanto. Utila por ĉiam disponeblaj fulmoklavoj."),
        ("Settings.CloseBehavior", "Konduto de la fermbutono"),
        ("Settings.MinimizeToTray", "Minimumigi al la sciiga areo"),
        ("Settings.MinimizeDescription", "La aplikaĵo daŭre funkcias. Uzu la piktogramon en la sciiga areo por montri aŭ eliri."),
        ("Settings.ExitApplication", "Eliri el la aplikaĵo"),
        ("Settings.ExitDescription", "La fermbutono tuj eliras. Aplikitaj reĝimaj agordoj restas, kaj fulmoklavoj ĉesas funkcii."),
        ("Settings.ShowTrayNotification", "Montri sciigon post minimumigo"),
        ("Settings.TrayNotificationDescription", "Montrata nur unufoje post ĉiu startigo."),
        ("Settings.VisibleModes", "Reĝimoj montrataj en la aplikaĵo"),
        ("Settings.VisibleModesDescription", "Elektu 1–5 aktivajn reĝimojn por la ĉefa ekrano. Trenu la kartojn por reordigi ilin."),
        ("Settings.ShowOnMain", "Montri en la ĉefa ekrano"),
        ("Settings.DeletePermanently", "Forigi definitive"),
        ("Settings.DeleteTip", "Forigas kopiitan aŭ novan reĝimon kun ĉiuj ĝiaj agordoj"),
        ("Settings.Shortcuts", "Fulmoklavoj por ŝanĝi reĝimon"),
        ("Settings.ShortcutsDescription", "Alklaku kampon kaj premu klavon kune kun Ctrl, Alt, Shift aŭ Win. La fulmoklavoj funkcias dum la aplikaĵo ruliĝas."),
        ("About.Title", "Pri PC Mode Switcher"),
        ("About.Description", "Ŝanĝu kune agordojn de Windows 11 por ludado, laboro, ĉiutaga uzo kaj pli."),
        ("About.ProjectLink", "Vidi la projekton en GitHub"),
        ("About.Version", "Versio {0}"),
        ("About.SupportTitle", "Subteni la evoluadon"),
        ("About.SupportKoFi", "Aĉeti al mi kafon per Ko-fi"),
        ("About.SupportPrivacy", "Ko-fi malfermiĝas en via retumilo. Ĉi tiu aplikaĵo ne kolektas aŭ konservas pagajn informojn."),
        ("Error.ExternalBrowser", "Ne eblis malfermi la eksteran retumilon."),
        ("Editor.Title", "Reĝimaj agordoj"),
        ("Editor.Description", "Elektu la agordojn aplikotajn kun ĉi tiu reĝimo."),
        ("Editor.DisplayAc", "Malŝalti ekranon (konektita)"),
        ("Editor.DisplayBattery", "Malŝalti ekranon (baterio)"),
        ("Editor.SleepAc", "Dormeto (konektita)"),
        ("Editor.SleepBattery", "Dormeto (baterio)"),
        ("Editor.PowerMode", "Energia reĝimo"),
        ("Editor.DefaultMicrophone", "Defaŭlta mikrofono"),
        ("Advanced.Basic", "Ĝenerala"),
        ("Advanced.Power", "Energio"),
        ("Advanced.Display", "Ekrano"),
        ("Advanced.Sound", "Sono"),
        ("Advanced.Apps", "Aplikaĵoj"),
        ("Advanced.Windows", "Fenestroj"),
        ("Advanced.ModeName", "Nomo de reĝimo"),
        ("Advanced.Icon", "Piktogramo"),
        ("Advanced.Status", "Stato"),
        ("Advanced.EnableMode", "Ebligi ĉi tiun reĝimon"),
        ("Advanced.ChangePowerPlan", "Ŝanĝi energiplanon"),
        ("Advanced.PowerPlan", "Energioplano"),
        ("Advanced.TargetMonitor", "Cela ekrano"),
        ("Advanced.RefreshRate", "Refreŝiga ofteco"),
        ("Advanced.TestRefreshRate", "Provi la refreŝigan oftecon"),
        ("Advanced.OutputVolume", "Eliga laŭteco"),
        ("Advanced.OutputMute", "Silentigi eligon"),
        ("Advanced.MicrophoneVolume", "Mikrofona laŭteco"),
        ("Advanced.MicrophoneMute", "Silentigi mikrofonon"),
        ("Advanced.AddExecutable", "Aldoni ruleblan dosieron"),
        ("Advanced.AddLink", "Aldoni ligilon"),
        ("Advanced.AddCloseTarget", "Aldoni fermendan celon"),
        ("Diagnostics.Title", "Diagnozo"),
        ("Diagnostics.Copy", "Kopii"),
        ("Diagnostics.OpenLogs", "Malfermi protokolojn"),
        ("Diagnostics.OpenSettings", "Malfermi agordojn"),
        ("Diagnostics.SaveReport", "Konservi raporton"),
        ("Diagnostics.BackupAll", "Sekurkopii ĉion"),
        ("DisplayConfirmation.Title", "Konfirmi ekranan agordon"),
        ("DisplayConfirmation.Heading", "Ĉu la ekrano aspektas ĝuste?"),
        ("DisplayConfirmation.Use", "Uzi ĉi tiun agordon"),
        ("Tray.Loading", "Ŝargante..."),
        ("Tray.Show", "Montri"),
        ("Tray.OpenSettings", "Malfermi agordojn"),
        ("Tray.Exit", "Eliri"),
        ("Status.Initial", "Elektu reĝimon por ŝanĝi la agordojn kune."),
        ("Status.Checking", "Kontrolante"),
        ("Status.ModeApplied", "Ŝanĝite al reĝimo {0}"),
        ("Status.ModePartiallyApplied", "Reĝimo {0} estis parte aplikita"),
        ("Status.ModeFailed", "Ne eblis apliki reĝimon {0}"),
        ("Status.ApplyingMode", "Aplikante reĝimon {0}..."),
        ("Status.ModeCopyName", "Kopio de {0}"),
        ("Mode.NewName", "Nova reĝimo"),
        ("Status.ModeSettingsSaved", "La agordoj de reĝimo {0} estis konservitaj."),
        ("Status.RestoredCount", "{0} elemento(j) restarigita(j)."),
        ("Status.SkippedCount", "{0} elemento(j) preterlasita(j)."),
        ("Status.MicrophoneOn", "Mikrofono ŜALTITA"),
        ("Status.MicrophoneOff", "Mikrofono MALŜALTITA"),
        ("Status.MicrophoneUnknown", "Mikrofono ?"),
        ("Card.AcBattery", "Konektita {0} / Baterio {1}"),
        ("Card.AcOnly", "Konektita {0}"),
        ("Card.Hours", "{0} h"),
        ("Card.Minutes", "{0} min"),
        ("Card.Seconds", "{0} s"),
        ("Card.VolumeMute", "Laŭteco {0}% / {1}"),
        ("Card.TrayDisplay", "Malŝalti ekranon: {0}"),
        ("Card.TraySleep", "Dormeto: {0}"),
        ("Card.TrayPower", "Energia reĝimo: {0}"),
        ("Card.TrayMicrophone", "Mikrofono (ĉe apliko): {0}"),
        ("Choice.OneHour", "1 horo"),
        ("Choice.TwoHours", "2 horoj"),
        ("Choice.ThreeHours", "3 horoj"),
        ("Choice.BestEfficiency", "Plej bona energia efikeco"),
        ("Choice.Balanced", "Ekvilibra"),
        ("Choice.BestPerformance", "Plej bona rendimento"),
        ("Choice.Disabled", "Malŝaltita"),
        ("Choice.PreventSleep", "Malhelpi nur dormeton"),
        ("Choice.PreventSleepDisplay", "Malhelpi dormeton kaj malŝalton de ekrano"),
        ("Choice.Mute", "Silentigi"),
        ("Choice.Unmute", "Malsilentigi"),
        ("Dialog.DeleteModeTitle", "Forigi reĝimon definitive"),
        ("Dialog.ForceKillTitle", "Averto pri deviga fermo"),
        ("Dialog.ReviewTitle", "Kontroli agojn")
    ];

    private static readonly (string Japanese, string Esperanto)[] EsperantoMessages =
    [
        ("予期しない問題が発生しました。操作を中止しました。", "Okazis neatendita problemo. La operacio estis haltigita."),
        ("確認中", "Kontrolante"),
        ("モードを選ぶと、設定をまとめて切り替えます。", "Elektu reĝimon por ŝanĝi la agordojn kune."),
        ("変更しない", "Ne ŝanĝi"),
        ("なし", "Neniam"),
        ("利用不可", "Nedisponebla"),
        ("不明", "Nekonata"),
        ("操作をキャンセルしました。", "La operacio estis nuligita."),
        ("モード設定を読み込みました。", "La reĝimaj agordoj estis importitaj."),
        ("モード設定を書き出しました。", "La reĝimaj agordoj estis eksportitaj."),
        ("モード設定を保存しました。", "La reĝimaj agordoj estis konservitaj."),
        ("モード設定を保存できませんでした。", "Ne eblis konservi la reĝimajn agordojn."),
        ("元に戻すための情報がありません。", "Ne estas informoj por restarigi."),
        ("元に戻すモードはありません。", "Ne estas reĝimo por restarigi."),
        ("すでに元に戻しています。", "Restarigo jam okazas."),
        ("表示言語が正しくありません。", "La montra lingvo ne validas.")
    ];

    private static readonly (string Key, string Value)[] SpanishUi =
    [
        ("Language.System", "Predeterminado (idioma de visualización de Windows)"),
        ("Language.Japanese", "Japonés"),
        ("Language.English", "Inglés"),
        ("Language.SimplifiedChinese", "Chino simplificado"),
        ("Language.TraditionalChinese", "Chino tradicional"),
        ("Language.Spanish", "Español"),
        ("Language.Arabic", "Árabe"),
        ("Language.Hindi", "Hindi"),
        ("Language.Esperanto", "Esperanto (experimental)"),
        ("Common.Apply", "Aplicar"),
        ("Common.Edit", "Editar"),
        ("Common.Cancel", "Cancelar"),
        ("Common.Save", "Guardar"),
        ("Common.Close", "Cerrar"),
        ("Common.Restore", "Restaurar"),
        ("Common.Duplicate", "Duplicar"),
        ("Common.Hide", "Ocultar"),
        ("Common.Clear", "Borrar"),
        ("Common.DeleteSelection", "Quitar selección"),
        ("Common.None", "Nunca"),
        ("Common.NoChange", "No cambiar"),
        ("Common.Unknown", "Desconocido"),
        ("Main.Menu.Mode", "Modo"),
        ("Main.Menu.RestorePreModeState", "Restaurar el estado previo a aplicar el modo"),
        ("Main.Menu.New", "Nuevo..."),
        ("Main.Menu.Import", "Importar configuración de modos..."),
        ("Main.Menu.Export", "Exportar configuración de modos..."),
        ("Main.Menu.Settings", "Configuración"),
        ("Main.Menu.AppSettings", "Configuración de la aplicación..."),
        ("Main.Menu.Diagnostics", "Diagnóstico..."),
        ("Main.Menu.Help", "Ayuda"),
        ("Update.CheckMenu", "Buscar actualizaciones..."),
        ("Main.Menu.Support", "Apoyar el desarrollo..."),
        ("Main.Menu.About", "Acerca de PC Mode Switcher"),
        ("Main.Tagline", "Cambia la configuración del PC con un clic según cómo lo uses."),
        ("Main.RestorePrompt", "¿Restaurar la configuración anterior?"),
        ("Main.CurrentMode", "MODO ACTUAL"),
        ("Main.Drag", "↔ Arrastra para reordenar"),
        ("Main.DragTip", "Arrastra a izquierda o derecha para cambiar el orden"),
        ("Main.DisplayOff", "APAGAR PANTALLA"),
        ("Main.Sleep", "SUSPENSIÓN"),
        ("Main.PowerMode", "MODO DE ENERGÍA"),
        ("Main.Microphone", "MICRÓFONO"),
        ("Main.Review", "Revisar acciones"),
        ("Main.HideTip", "Oculta este modo de la aplicación sin borrar su configuración"),
        ("Update.Available", "Hay una nueva versión disponible: {0}"),
        ("Update.ViewRelease", "Ver novedades"),
        ("Update.Dismiss", "Ocultar esta versión"),
        ("Update.Title", "Buscar actualizaciones"),
        ("Update.ManualAvailable", "Hay una nueva versión disponible: {0}.\n\n¿Abrir las novedades en GitHub?"),
        ("Update.UpToDate", "{0} está actualizado."),
        ("Update.CheckFailed", "No se pudieron buscar actualizaciones. Inténtalo de nuevo más tarde."),
        ("Update.NoReleasePage", "No se pudo abrir la página de actualización."),
        ("Update.NotificationTitle", "Actualización de PC Mode Switcher"),
        ("Settings.Title", "Configuración de la aplicación"),
        ("Settings.Description", "Configura el idioma, los modos visibles, el inicio, el botón de cierre y los atajos."),
        ("Settings.Language", "Idioma"),
        ("Settings.LanguageDescription", "De forma predeterminada se usa el idioma de Windows. También puedes elegir japonés, inglés, chino simplificado, chino tradicional, español, árabe, hindi o esperanto experimental."),
        ("Settings.Updates", "Actualizaciones"),
        ("Settings.CheckForUpdatesAutomatically", "Buscar nuevas versiones automáticamente"),
        ("Settings.UpdateDescription", "Busca actualizaciones 30 segundos después del inicio y cada 24 horas. Solo avisa cuando hay una nueva versión."),
        ("Settings.MicrophoneFeature", "Controles del micrófono"),
        ("Settings.EnableMicrophone", "Activar la visualización y los controles del micrófono"),
        ("Settings.MicrophoneDescription", "Al desactivarlo, se ocultan las opciones del micrófono y los modos no lo modifican. La configuración guardada se conserva."),
        ("Settings.Startup", "Inicio de sesión de Windows"),
        ("Settings.StartWithWindows", "Iniciar automáticamente al entrar en Windows"),
        ("Settings.StartupDescription", "Solo se aplica al usuario actual. Es útil para tener los atajos siempre disponibles."),
        ("Settings.CloseBehavior", "Comportamiento del botón de cierre"),
        ("Settings.MinimizeToTray", "Minimizar al área de notificación"),
        ("Settings.MinimizeDescription", "La aplicación sigue funcionando. Puedes mostrarla o cerrarla desde el icono del área de notificación."),
        ("Settings.ExitApplication", "Salir de la aplicación"),
        ("Settings.ExitDescription", "El botón de cierre sale inmediatamente. La configuración del modo aplicado se mantiene y los atajos dejan de funcionar."),
        ("Settings.ShowTrayNotification", "Mostrar una notificación al minimizar"),
        ("Settings.TrayNotificationDescription", "Solo se muestra una vez después de iniciar la aplicación."),
        ("Settings.VisibleModes", "Modos mostrados en la aplicación"),
        ("Settings.VisibleModesDescription", "Elige de 1 a 5 modos activos para la pantalla principal. Arrastra las tarjetas para reordenarlas."),
        ("Settings.ShowOnMain", "Mostrar en la pantalla principal"),
        ("Settings.DeletePermanently", "Eliminar permanentemente"),
        ("Settings.DeleteTip", "Elimina un modo duplicado o nuevo junto con toda su configuración"),
        ("Settings.Shortcuts", "Atajos para cambiar de modo"),
        ("Settings.ShortcutsDescription", "Haz clic en un campo y pulsa una tecla junto con Ctrl, Alt, Mayús o Win. Los atajos funcionan mientras la aplicación esté abierta, incluso en otras ventanas."),
        ("About.Title", "Acerca de PC Mode Switcher"),
        ("About.Description", "Cambia en conjunto la configuración de Windows 11 para jugar, trabajar, el uso diario y mucho más."),
        ("About.ProjectLink", "Ver el proyecto en GitHub"),
        ("About.Version", "Versión {0}"),
        ("About.SupportTitle", "Apoyar el desarrollo"),
        ("About.SupportDescription", "PC Mode Switcher es gratuito y ofrece todas sus funciones sin límites. Si te resulta útil, puedes hacer una aportación única del importe que prefieras en Ko-fi (unos 500 JPY, el precio de un café)."),
        ("About.SupportKoFi", "Invítame a un café en Ko-fi"),
        ("About.SupportPrivacy", "Ko-fi se abre en el navegador. Esta aplicación no recopila ni guarda información de pago."),
        ("Error.ExternalBrowser", "No se pudo abrir el navegador externo."),
        ("Editor.Title", "Configuración del modo"),
        ("Editor.Description", "Elige la configuración que se aplicará con este modo."),
        ("Editor.DisplayAc", "Apagar pantalla (conectado)"),
        ("Editor.DisplayBattery", "Apagar pantalla (con batería)"),
        ("Editor.SleepAc", "Suspensión (conectado)"),
        ("Editor.SleepBattery", "Suspensión (con batería)"),
        ("Editor.PowerMode", "Modo de energía"),
        ("Editor.DefaultMicrophone", "Micrófono predeterminado"),
        ("Advanced.Basic", "General"),
        ("Advanced.Power", "Energía"),
        ("Advanced.Display", "Pantalla"),
        ("Advanced.Sound", "Audio"),
        ("Advanced.Apps", "Aplicaciones"),
        ("Advanced.Windows", "Ventanas"),
        ("Advanced.ModeName", "Nombre del modo"),
        ("Advanced.Icon", "Icono"),
        ("Advanced.Status", "Estado"),
        ("Advanced.EnableMode", "Activar este modo"),
        ("Advanced.RestoreDescription", "La aplicación registra el estado actual antes de aplicar un modo. Restaurar intenta devolver únicamente la configuración modificada por esta aplicación."),
        ("Advanced.ChangePowerPlan", "Cambiar el plan de energía"),
        ("Advanced.PowerPlan", "Plan de energía"),
        ("Advanced.PowerModeAc", "Modo de energía (conectado)"),
        ("Advanced.PowerModeBattery", "Modo de energía (con batería)"),
        ("Advanced.DisplayTimeout", "Apagar la pantalla después de (conectado / batería)"),
        ("Advanced.SleepTimeout", "Suspender después de (conectado / batería)"),
        ("Advanced.SleepPrevention", "Impedir temporalmente la suspensión"),
        ("Advanced.PowerRestoreDescription", "Si se cambia un tiempo de espera de otro plan, se restauran tanto su valor original como el plan que estaba activo antes del modo."),
        ("Advanced.TargetMonitor", "Monitor de destino"),
        ("Advanced.RefreshRate", "Frecuencia de actualización (mantiene resolución, profundidad de color y orientación)"),
        ("Advanced.TestRefreshRate", "Probar esta frecuencia de actualización"),
        ("Advanced.RefreshRateDescription", "Después de que Windows confirme que está disponible, se aplica temporalmente. Si no eliges «Usar esta configuración» en 15 segundos, se restaura automáticamente. Vuelve a probarla si cambias los monitores o su disposición."),
        ("Advanced.OutputVolume", "Volumen de salida predeterminado (0–100)"),
        ("Advanced.OutputMute", "Silenciar salida predeterminada"),
        ("Advanced.MicrophoneVolume", "Volumen del micrófono predeterminado (0–100)"),
        ("Advanced.MicrophoneMute", "Silenciar micrófono predeterminado"),
        ("Advanced.BlankNoChange", "Déjalo vacío para no cambiarlo"),
        ("Advanced.LaunchTarget", "Aplicación o enlace web que se abrirá"),
        ("Advanced.LaunchArguments", "Opciones de inicio (separadas por |)"),
        ("Advanced.WorkingDirectory", "Carpeta de inicio (opcional)"),
        ("Advanced.Delay", "Retraso (ms)"),
        ("Advanced.Order", "Orden"),
        ("Advanced.AdditionalInstance", "Abrir otra instancia si ya está en ejecución"),
        ("Advanced.CloseOnRestore", "Cerrar al restaurar"),
        ("Advanced.AddExecutable", "Añadir ejecutable..."),
        ("Advanced.AddLink", "Añadir enlace web u otro destino"),
        ("Advanced.CloseTarget", "Ejecutable que se cerrará al iniciar el modo"),
        ("Advanced.GracePeriod", "Espera antes de cerrar (s)"),
        ("Advanced.AllowForceKill", "Permitir cierre forzado"),
        ("Advanced.RestartOnRestore", "Reiniciar al restaurar"),
        ("Advanced.RestartArguments", "Opciones de reinicio (separadas por |)"),
        ("Advanced.RestartDirectory", "Carpeta de reinicio (opcional)"),
        ("Advanced.AddCloseTarget", "Añadir destino de cierre..."),
        ("Advanced.MonitorTarget", "Aplicación que debe cerrarse antes de la restauración automática"),
        ("Advanced.AddMonitorTarget", "Añadir aplicación que se esperará"),
        ("Advanced.CaptureWindows", "Guardar la disposición actual de las ventanas"),
        ("Advanced.WindowDescription", "La aplicación espera hasta 15 segundos, en intervalos de 0,5 segundos, a que aparezcan las ventanas. Si un monitor guardado no está disponible, las mueve al monitor principal y continúa aunque alguna no pueda moverse."),
        ("Diagnostics.ReportTitle", "Informe de diagnóstico de PC Mode Switcher"),
        ("Diagnostics.GeneratedUtc", "Generado (UTC): {0}"),
        ("Diagnostics.AppVersion", "Aplicación: {0}"),
        ("Diagnostics.WindowsPowerMode", "Cambios del modo de energía de Windows 11: {0}"),
        ("Diagnostics.Available", "Disponible"),
        ("Diagnostics.Unavailable", "No disponible"),
        ("Diagnostics.CurrentPowerPlan", "Plan de energía actual: {0}"),
        ("Diagnostics.AvailablePowerPlans", "Planes de energía disponibles:"),
        ("Diagnostics.Active", "[activo]"),
        ("Diagnostics.SleepPreventionAvailable", "Impedir la suspensión mientras un modo está activo: disponible"),
        ("Diagnostics.ConnectedMonitors", "Monitores conectados:"),
        ("Diagnostics.MonitorLine", "  - {0} {1}x{2} {3}Hz / disponibles: {4}"),
        ("Diagnostics.DefaultOutput", "Salida de audio predeterminada"),
        ("Diagnostics.DefaultMicrophone", "Micrófono predeterminado"),
        ("Diagnostics.RestorableNone", "Configuración de modo restaurable: ninguna"),
        ("Diagnostics.RestorableSession", "Configuración de modo restaurable: {0} / {1} / iniciada {2}"),
        ("Diagnostics.LogFolder", "Carpeta de registros: {0}"),
        ("Diagnostics.SettingsFolder", "Carpeta de configuración: {0}"),
        ("Diagnostics.PowerValue", "{0}: conectado {1} s / batería {2} s"),
        ("Diagnostics.AudioState", "{0}: ID={1}, volumen={2}, silenciado={3}"),
        ("Diagnostics.DryRunHeading", "Acciones de {0} (no se cambiará la configuración)"),
        ("Diagnostics.ChangePlan", "✓ Cambiar el plan de energía a «{0}»"),
        ("Diagnostics.PlanUnavailable", "⚠ El plan de energía seleccionado no está disponible"),
        ("Diagnostics.PlanNoChange", "– No cambiar el plan de energía"),
        ("Diagnostics.SleepPreventionDisabled", "– La prevención temporal de suspensión está desactivada"),
        ("Diagnostics.SleepPrevention", "✓ Prevención temporal de suspensión: {0}"),
        ("Diagnostics.RefreshNoChange", "– No cambiar la frecuencia de actualización"),
        ("Diagnostics.RefreshChange", "{0} Cambiar {1} a {2}Hz"),
        ("Diagnostics.AudioNoChange", "– No cambiar {0}"),
        ("Diagnostics.AudioChange", "✓ {0}: volumen {1}% / {2}"),
        ("Diagnostics.CloseTarget", "✓ Solicitar el cierre normal de {0}"),
        ("Diagnostics.CloseMissing", "⚠ No se encontró el destino de cierre: {0}"),
        ("Diagnostics.Launch", "✓ Abrir: {0}"),
        ("Diagnostics.LaunchMissing", "⚠ No se encontró el destino que se debía abrir: {0}"),
        ("Diagnostics.WindowPlacements", "✓ Esperar hasta 15 segundos y aplicar {0} posición(es) de ventana"),
        ("Diagnostics.AutoRestore", "✓ Restaurar automáticamente cuando se cierren {0} aplicación(es) indicadas"),
        ("Diagnostics.PreventSleep", "Impedir la suspensión del PC"),
        ("Diagnostics.PreventSleepDisplay", "Impedir la suspensión del PC y el apagado de la pantalla"),
        ("Hotkey.Invalid", "El atajo de {0} no es válido."),
        ("Hotkey.Duplicate", "No se puede asignar el mismo atajo «{0}» a varios modos."),
        ("Hotkey.RegistrationFailed", "No se pudo registrar el atajo «{1}» de {0}. Elige una combinación que no use otra aplicación ni Windows."),
        ("Hotkey.RollbackFailed", "{0} Tampoco se pudieron restaurar los atajos anteriores."),
        ("Diagnostics.Title", "Diagnóstico"),
        ("Diagnostics.Copy", "Copiar al portapapeles"),
        ("Diagnostics.OpenLogs", "Abrir la carpeta de registros"),
        ("Diagnostics.OpenSettings", "Abrir la carpeta de configuración"),
        ("Diagnostics.SaveReport", "Guardar informe"),
        ("Diagnostics.BackupAll", "Crear una copia de toda la configuración"),
        ("DisplayConfirmation.Title", "Confirmar configuración de pantalla"),
        ("DisplayConfirmation.Heading", "Mostrando la nueva frecuencia de actualización"),
        ("DisplayConfirmation.Use", "Usar esta configuración"),
        ("Tray.Loading", "Cargando modos..."),
        ("Tray.Show", "Mostrar"),
        ("Tray.OpenSettings", "Abrir configuración"),
        ("Tray.Exit", "Salir"),
        ("Status.Initial", "Elige un modo para cambiar su configuración en conjunto."),
        ("Status.Checking", "Comprobando"),
        ("Status.ModeApplied", "Se cambió al modo {0}"),
        ("Status.ModePartiallyApplied", "El modo {0} se aplicó parcialmente"),
        ("Status.ModeFailed", "No se pudo aplicar el modo {0}"),
        ("Status.ApplyingMode", "Aplicando el modo {0}..."),
        ("Status.SettingsSavedDeleted", "Se guardó la configuración y se eliminaron {0} modo(s) añadido(s)."),
        ("Status.ModeCopyName", "Copia de {0}"),
        ("Mode.NewName", "Modo nuevo"),
        ("Status.ModeSettingsSaved", "Se guardó la configuración del modo {0}."),
        ("Status.RestoredCount", "Se restauraron {0} elemento(s)."),
        ("Status.SkippedCount", "Se omitieron {0} elemento(s)."),
        ("Status.RestoreFailedCount", "No se pudieron restaurar {0} elemento(s). Consulta Diagnóstico para obtener más información."),
        ("Status.MicrophoneOn", "Micrófono ACTIVADO"),
        ("Status.MicrophoneOff", "Micrófono DESACTIVADO"),
        ("Status.MicrophoneUnknown", "Micrófono ?"),
        ("Status.MicrophoneOnTip", "El micrófono de Windows está activado. Haz clic para silenciarlo."),
        ("Status.MicrophoneOffTip", "El micrófono de Windows está silenciado. Haz clic para activarlo."),
        ("Status.MicrophoneUnknownTip", "No se conoce el estado del micrófono de Windows. Haz clic para comprobarlo de nuevo."),
        ("Status.MicrophoneChanged", "El micrófono se estableció en {0}."),
        ("Status.MicrophoneSummary", "Micrófono: {0}"),
        ("Status.MicrophoneNoChangeCurrent", "Micrófono: no cambiar (actual: {0})"),
        ("Status.MicrophoneNoChangeUnknown", "Micrófono: no cambiar (estado actual no disponible)"),
        ("Card.AcBattery", "Conectado {0} / Batería {1}"),
        ("Card.AcOnly", "Conectado {0}"),
        ("Card.Hours", "{0} h"),
        ("Card.Minutes", "{0} min"),
        ("Card.Seconds", "{0} s"),
        ("Card.VolumeMute", "Volumen {0}% / {1}"),
        ("Card.TrayDisplay", "Apagar pantalla: {0}"),
        ("Card.TraySleep", "Suspensión: {0}"),
        ("Card.TrayPower", "Modo de energía: {0}"),
        ("Card.TrayMicrophone", "Micrófono (al aplicar): {0}"),
        ("Choice.OneHour", "1 hora"),
        ("Choice.TwoHours", "2 horas"),
        ("Choice.ThreeHours", "3 horas"),
        ("Choice.BestEfficiency", "Máxima eficiencia energética"),
        ("Choice.Balanced", "Equilibrado"),
        ("Choice.BestPerformance", "Máximo rendimiento"),
        ("Choice.Disabled", "Desactivado"),
        ("Choice.PreventSleep", "Impedir solo la suspensión"),
        ("Choice.PreventSleepDisplay", "Impedir la suspensión y el apagado de la pantalla"),
        ("Choice.Mute", "Silenciar"),
        ("Choice.Unmute", "Dejar de silenciar"),
        ("Advanced.Verified", "Verificado"),
        ("Advanced.Unverified", "No verificado (requiere una prueba)"),
        ("Advanced.SavedWindows", "Guardadas: {0} ventana(s)"),
        ("DisplayConfirmation.Message", "¿Usar {0} Hz? Se restaurará automáticamente si no lo confirmas en {1} segundos."),
        ("Dialog.DeleteMode", "¿Eliminar «{0}» permanentemente?\n\nLa eliminación no será definitiva hasta que selecciones Guardar."),
        ("Dialog.DeleteModeTitle", "Eliminar modo permanentemente"),
        ("Dialog.HideMode", "¿Ocultar este modo de la aplicación?\n\nSu configuración no se eliminará y podrás volver a mostrarlo desde Configuración."),
        ("Dialog.ForceKill", "El cierre forzado puede descartar datos no guardados de la aplicación de destino. ¿Continuar?"),
        ("Dialog.ForceKillTitle", "Advertencia de cierre forzado"),
        ("Dialog.ReviewTitle", "Revisar acciones"),
        ("File.SettingsFilter", "Configuración de PC Mode Switcher (*.json)|*.json"),
        ("File.TextFilter", "Archivos de texto (*.txt)|*.txt"),
        ("File.ExecutableFilter", "Archivos ejecutables (*.exe)|*.exe"),
        ("File.ExecutableAllFilter", "Archivos ejecutables (*.exe)|*.exe|Todos los archivos (*.*)|*.*"),
        ("Tray.MinimizedHint", "Se minimizó al área de notificación. Haz doble clic para mostrar la aplicación o haz clic con el botón derecho y elige Salir."),
        ("Tray.AppliedSettings", "Se aplicó la configuración registrada en este modo."),
        ("Dialog.AutomaticRecoveryFailed", "La aplicación del modo se interrumpió y se revirtió automáticamente, pero algunos elementos no pudieron restaurarse.\n\n{0}"),
    ];

    private static readonly (string Japanese, string Spanish)[] SpanishMessages =
    [
        ("予期しない問題が発生しました。操作を中止しました。", "Se produjo un problema inesperado. La operación se detuvo."),
        ("確認中", "Comprobando"),
        ("モードを選ぶと、設定をまとめて切り替えます。", "Elige un modo para cambiar su configuración en conjunto."),
        ("変更しない", "No cambiar"),
        ("設定エラー", "Error de configuración"),
        ("ミュート変更なし", "No cambiar el silencio"),
        ("なし", "Nunca"),
        ("利用不可", "No disponible"),
        ("未登録の設定", "Configuración no registrada"),
        ("確認できません", "No se puede determinar"),
        ("バージョン不明", "Versión desconocida"),
        ("初期設定で開始しました。", "Se inició con la configuración predeterminada."),
        ("閉じるボタンの動作が正しくありません。", "El comportamiento del botón de cierre no es válido."),
        ("標準モードは完全削除できません。非表示または無効にしてください。", "Los modos integrados no se pueden eliminar permanentemente. Ocúltalos o desactívalos."),
        ("削除するモードが見つかりません。", "No se encontró el modo que se debía eliminar."),
        ("有効なモードを1個以上選んでください。", "Selecciona al menos un modo activo."),
        ("アプリ画面に表示するモードは1〜5個で選んでください。", "Elige de 1 a 5 modos para mostrarlos en la aplicación."),
        ("アプリ設定を保存しました。", "Se guardó la configuración de la aplicación."),
        ("既定のマイクの状態を確認できないため、切り替えませんでした。", "No se pudo determinar el estado del micrófono predeterminado, por lo que no se modificó."),
        ("現在の状態は再確認できませんでした。", "No se pudo volver a comprobar el estado actual."),
        ("モード適用前の状態へ戻しています…", "Restaurando el estado anterior a la aplicación del modo..."),
        ("複製元のモードが見つかりません。", "No se encontró el modo de origen."),
        ("非表示にするモードが画面に見つかりません。", "No se encontró en la pantalla el modo que se debía ocultar."),
        ("最後の表示モードは非表示にできません。", "No se puede ocultar el último modo visible."),
        ("モードをアプリ画面から非表示にしました。設定から再表示できます。", "El modo se ocultó de la aplicación. Puedes volver a mostrarlo desde Configuración."),
        ("並べ替えるモードが画面に見つかりません。", "No se encontró en la pantalla el modo que se debía reordenar."),
        ("モードの表示順を変更しました。", "Se cambió el orden de visualización de los modos."),
        ("モード設定を読み込みました。", "Se importó la configuración de los modos."),
        ("モード設定を書き出しました。", "Se exportó la configuración de los modos."),
        ("モード設定を書き出せませんでした。", "No se pudo exportar la configuración de los modos."),
        ("モード設定を読み込めませんでした。", "No se pudo importar la configuración de los modos."),
        ("保存済みのモード設定を読み込めませんでした。", "No se pudo cargar la configuración guardada de los modos."),
        ("設定ファイルはこのアプリより新しい形式です。上書きしません。", "El archivo de configuración usa un formato más reciente y no se sobrescribirá."),
        ("読み込むファイルの形式が正しくありません。", "El formato del archivo seleccionado no es válido."),
        ("モード設定が正しくないため保存しませんでした。", "La configuración de los modos no es válida y no se guardó."),
        ("モード設定を保存しました。", "Se guardó la configuración de los modos."),
        ("モード設定を保存できませんでした。", "No se pudo guardar la configuración de los modos."),
        ("バックアップを作成できませんでした。", "No se pudo crear la copia de seguridad."),
        ("マイク設定が正しくありません。", "La configuración del micrófono no es válida."),
        ("マイクのミュート状態は変更しませんでした。", "No se cambió el estado de silencio del micrófono."),
        ("電源モードが選択されていません。", "No hay ningún modo de energía seleccionado."),
        ("選択した電源モードはこのPCで利用できません。", "El modo de energía seleccionado no está disponible en este PC."),
        ("電源モードを切り替えました。", "Se cambió el modo de energía."),
        ("電源モードの切り替えを確認できませんでした。", "No se pudo verificar el cambio del modo de energía."),
        ("現在のWindows電源設定を確認できませんでした。", "No se pudo determinar la configuración de energía actual de Windows."),
        ("利用可能な電源プランがありません。", "No hay planes de energía disponibles."),
        ("元に戻すための情報がありません。", "No hay información disponible para restaurar."),
        ("変更しない設定です。", "Esta configuración no se modificará."),
        ("Windows 11でのみ利用できます。", "Esta función solo está disponible en Windows 11."),
        ("このWindowsでは電源モードを変更できません。", "Esta versión de Windows no permite cambiar el modo de energía."),
        ("Windowsへ電源モードを要求しました。", "Se solicitó el modo de energía a Windows."),
        ("電源モードを要求できませんでした。", "No se pudo solicitar el modo de energía."),
        ("使用しない設定です。", "Esta configuración está desactivada."),
        ("自動スリープを一時的に防止しました。", "Se impidió temporalmente la suspensión automática."),
        ("一時的なスリープ防止を解除しました。", "Finalizó la prevención temporal de suspensión."),
        ("登録項目がありません。", "No hay elementos registrados."),
        ("実行ファイルが見つかりません。", "No se encontró el archivo ejecutable."),
        ("プロセスを開始できませんでした。", "No se pudo iniciar el proceso."),
        ("操作をキャンセルしました。", "Se canceló la operación."),
        ("現在状態を記録できないため変更しません。", "No se pudo registrar el estado actual, por lo que no se hizo ningún cambio."),
        ("適用中に予期しない問題が発生しました。", "Se produjo un problema inesperado al aplicar el modo."),
        ("元に戻す途中で予期しない問題が発生しました。", "Se produjo un problema inesperado durante la restauración."),
        ("元に戻すモードはありません。", "No hay ningún modo que restaurar."),
        ("すでに元に戻しています。", "La restauración ya está en curso."),
        ("スタートアップ設定を開けませんでした。", "No se pudo abrir la configuración de inicio."),
        ("アプリの実行ファイルを特定できないため、スタートアップへ登録できませんでした。", "No se pudo identificar el ejecutable de la aplicación, por lo que falló el registro de inicio."),
        ("スタートアップ設定を変更できませんでした。", "No se pudo cambiar la configuración de inicio."),
        ("すべての設定を選択してください。", "Selecciona todas las opciones."),
        ("モニターとリフレッシュレートを選択してください。", "Selecciona un monitor y una frecuencia de actualización."),
        ("モード名を入力してください。", "Escribe un nombre para el modo."),
        ("電源プランを選択してください。", "Selecciona un plan de energía."),
        ("音量は空欄（変更しない）または0～100で入力してください。", "Deja el volumen vacío para no cambiarlo o introduce un valor entre 0 y 100."),
        ("Ctrl、Alt、Shift、Winのいずれかを同時に押してください。", "Pulsa una tecla junto con Ctrl, Alt, Mayús o Win."),
        ("アプリ画面に表示できるモードは最大5個です。", "Se pueden mostrar hasta cinco modos en la aplicación."),
        ("表示するモードを1個以上選んでください。", "Selecciona al menos un modo para mostrar."),
        ("表示言語が正しくありません。", "El idioma de visualización no es válido.")
    ];

    private static void ConvertToSimplifiedChinese(Dictionary<string, string> values)
    {
        foreach (var key in values.Keys.ToArray())
        {
            var converted = ToSimplifiedChinese(values[key]);
            foreach (var (from, to) in MainlandChineseVocabulary)
                converted = converted.Replace(from, to, StringComparison.Ordinal);
            values[key] = converted;
        }

        values["Language.SimplifiedChinese"] = "简体中文";
        values["Language.TraditionalChinese"] = "繁体中文";
        values["Language.Spanish"] = "西班牙语";
        values["Language.Arabic"] = "阿拉伯语";
        values["Language.Hindi"] = "印地语";
        values["Language.Esperanto"] = "世界语（实验性）";
        values["Settings.LanguageDescription"] =
            "默认使用 Windows 显示语言。也可以固定为日语、英语、简体中文、繁体中文、西班牙语、阿拉伯语、印地语或实验性的世界语。";
    }

    private static string ToSimplifiedChinese(string value)
    {
        var length = LCMapStringEx(
            "zh-CN", SimplifiedChineseMapFlag, value, -1,
            null, 0, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
        if (length <= 0)
            return value;

        var output = new StringBuilder(length);
        return LCMapStringEx(
                   "zh-CN", SimplifiedChineseMapFlag, value, -1,
                   output, output.Capacity, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero) > 0
            ? output.ToString()
            : value;
    }

    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern int LCMapStringEx(
        string localeName,
        uint mapFlags,
        string source,
        int sourceLength,
        StringBuilder? destination,
        int destinationLength,
        IntPtr versionInformation,
        IntPtr reserved,
        IntPtr sortHandle);

    private static void AddSpanishOverrides(Dictionary<string, string> values)
    {
        foreach (var (key, value) in SpanishUi)
            values[key] = value;
        foreach (var (japanese, spanish) in SpanishMessages)
            values["Message." + japanese] = spanish;
    }

    private static void AddEsperantoOverrides(Dictionary<string, string> values)
    {
        foreach (var (key, value) in EsperantoUi)
            values[key] = value;
        foreach (var (japanese, esperanto) in EsperantoMessages)
            values["Message." + japanese] = esperanto;
    }
}
