namespace PCModeSwitcher.Services;

internal static partial class LocalizationStrings
{
    private static readonly (string Key, string Ja, string En, string Zh)[] Ui =
    [
        ("Language.System", "既定値（Windows の表示言語）", "Default (Windows display language)", "預設值（Windows 顯示語言）"),
        ("Language.Japanese", "日本語", "Japanese", "日文"),
        ("Language.English", "English", "English", "英文"),
        ("Language.TraditionalChinese", "繁體中文", "Traditional Chinese", "繁體中文"),
        ("Common.Apply", "適用", "Apply", "套用"),
        ("Common.Edit", "編集", "Edit", "編輯"),
        ("Common.Cancel", "キャンセル", "Cancel", "取消"),
        ("Common.Save", "保存", "Save", "儲存"),
        ("Common.Close", "閉じる", "Close", "關閉"),
        ("Common.Restore", "元に戻す", "Restore", "還原"),
        ("Common.Duplicate", "複製", "Duplicate", "複製"),
        ("Common.Hide", "非表示", "Hide", "隱藏"),
        ("Common.Clear", "解除", "Clear", "清除"),
        ("Common.DeleteSelection", "選択を削除", "Remove selected", "刪除選取項目"),
        ("Common.None", "なし", "Never", "永不"),
        ("Common.NoChange", "変更しない", "Do not change", "不變更"),
        ("Common.Unknown", "不明", "Unknown", "不明"),
        ("Main.Menu.Mode", "モード", "Mode", "模式"),
        ("Main.Menu.New", "新規作成...", "New...", "新增..."),
        ("Main.Menu.Import", "モード設定を読み込む...", "Import mode settings...", "匯入模式設定..."),
        ("Main.Menu.Export", "モード設定を書き出す...", "Export mode settings...", "匯出模式設定..."),
        ("Main.Menu.Settings", "設定", "Settings", "設定"),
        ("Main.Menu.AppSettings", "アプリ設定...", "App settings...", "應用程式設定..."),
        ("Main.Menu.Diagnostics", "診断...", "Diagnostics...", "診斷..."),
        ("Main.Menu.Help", "ヘルプ", "Help", "說明"),
        ("Main.Menu.About", "このソフトについて", "About PC Mode Switcher", "關於 PC Mode Switcher"),
        ("Main.Tagline", "使い方に合わせて、PC設定を1クリックで切り替えます。", "Switch PC settings for the way you use it with one click.", "只要按一下，即可依使用情境切換電腦設定。"),
        ("Main.CurrentMode", "現在のモード", "CURRENT MODE", "目前模式"),
        ("Main.Drag", "↔ ドラッグで並べ替え", "↔ Drag to reorder", "↔ 拖曳以排序"),
        ("Main.DragTip", "つかんで左右へドラッグすると表示順を変更できます", "Drag left or right to change the display order", "向左或向右拖曳以變更顯示順序"),
        ("Main.DisplayOff", "画面OFF", "TURN OFF DISPLAY", "關閉螢幕"),
        ("Main.Sleep", "スリープ", "SLEEP", "睡眠"),
        ("Main.PowerMode", "電源モード", "POWER MODE", "電源模式"),
        ("Main.Microphone", "マイク", "MICROPHONE", "麥克風"),
        ("Main.Review", "実行内容を確認", "Review actions", "檢視執行內容"),
        ("Main.HideTip", "モード設定は残したまま、アプリ画面から隠します", "Hide this mode from the app while keeping its settings", "保留模式設定，只從應用程式畫面隱藏"),
        ("Settings.Title", "アプリ設定", "App settings", "應用程式設定"),
        ("Settings.Description", "表示言語、表示するモード、起動方法、閉じるボタン、切り替えキーを設定します。", "Configure the display language, visible modes, startup, close button, and shortcuts.", "設定顯示語言、顯示模式、啟動方式、關閉按鈕及快速鍵。"),
        ("Settings.Language", "表示言語", "Display language", "顯示語言"),
        ("Settings.LanguageDescription", "既定値ではWindowsの表示言語を使います。日本語・English・繁體中文から固定することもできます。", "Default follows the Windows display language. You can also lock the app to Japanese, English, or Traditional Chinese.", "預設值會依照 Windows 顯示語言。也可以固定使用日文、英文或繁體中文。"),
        ("Settings.MicrophoneFeature", "マイク機能", "Microphone controls", "麥克風功能"),
        ("Settings.EnableMicrophone", "マイク関連の表示と操作を有効にする", "Enable microphone displays and controls", "啟用麥克風顯示與操作"),
        ("Settings.MicrophoneDescription", "OFFにすると画面とモード編集からマイク項目を隠し、モード適用時もマイクを変更しません。保存済みのマイク設定は保持されます。", "When off, microphone options are hidden and applying a mode will not change the microphone. Saved settings are kept.", "關閉後會隱藏畫面及模式編輯中的麥克風項目，套用模式時也不變更麥克風。已儲存的設定會保留。"),
        ("Settings.Startup", "Windowsログイン時の起動", "Start at Windows sign-in", "Windows 登入時啟動"),
        ("Settings.StartWithWindows", "Windowsにログインしたとき自動的に起動", "Start automatically when I sign in to Windows", "登入 Windows 時自動啟動"),
        ("Settings.StartupDescription", "現在のユーザーだけに適用されます。ショートカットを常時使う場合に便利です。", "Applies only to the current user. Useful when you want shortcuts available at all times.", "只套用至目前使用者。適合需要隨時使用快速鍵時啟用。"),
        ("Settings.CloseBehavior", "閉じるボタンの動作", "Close button behavior", "關閉按鈕動作"),
        ("Settings.MinimizeToTray", "通知領域に格納", "Minimize to notification area", "縮小至通知區域"),
        ("Settings.MinimizeDescription", "アプリは動作を続けます。通知領域アイコンから再表示・終了できます。", "The app keeps running. Use the notification-area icon to show or exit it.", "應用程式會繼續執行。可從通知區域圖示重新顯示或結束。"),
        ("Settings.ExitApplication", "アプリを終了", "Exit the app", "結束應用程式"),
        ("Settings.ExitDescription", "閉じるボタンでアプリを完全に終了します。ショートカットも停止します。", "The close button exits the app completely and disables its shortcuts.", "按下關閉按鈕會完全結束應用程式，快速鍵也會停止。"),
        ("Settings.ShowTrayNotification", "通知領域へ格納したときに通知を表示", "Show a notification when minimized", "縮小至通知區域時顯示通知"),
        ("Settings.TrayNotificationDescription", "通知はアプリを起動してから最初の1回だけ表示します。", "Shown only once after each app launch.", "每次啟動應用程式後只顯示一次。"),
        ("Settings.VisibleModes", "アプリ画面に表示するモード", "Modes shown in the app", "應用程式畫面顯示的模式"),
        ("Settings.VisibleModesDescription", "有効なモードからメイン表示する1〜5個を選べます。並び順はメイン画面でドラッグして変更できます。", "Choose 1–5 enabled modes for the main screen. Drag cards there to reorder them.", "可從啟用的模式中選擇 1～5 個顯示在主畫面，並在主畫面拖曳卡片調整順序。"),
        ("Settings.ShowOnMain", "メイン表示", "Show on main screen", "顯示於主畫面"),
        ("Settings.DeletePermanently", "完全削除", "Delete permanently", "永久刪除"),
        ("Settings.DeleteTip", "複製・新規作成したモードを設定ごと削除します", "Delete a duplicated or newly created mode and all its settings", "刪除複製或新增的模式及其全部設定"),
        ("Settings.Shortcuts", "モード切り替えショートカット", "Mode-switching shortcuts", "模式切換快速鍵"),
        ("Settings.ShortcutsDescription", "入力欄をクリックして、Ctrl／Alt／Shift／Winのいずれかとキーを同時に押します。アプリが動作中なら、他の画面を操作していても使えます。", "Click a field, then press a key together with Ctrl, Alt, Shift, or Win. Shortcuts work while the app is running, even in other windows.", "按一下輸入欄位，再同時按下 Ctrl、Alt、Shift 或 Win 與另一按鍵。應用程式執行時，即使操作其他視窗也能使用。"),
        ("About.Title", "このソフトについて", "About PC Mode Switcher", "關於 PC Mode Switcher"),
        ("About.Description", "ゲーム、仕事、普段使いなどに合わせて、Windows 11の設定をまとめて切り替えるアプリです。", "Switch Windows 11 settings together for gaming, work, everyday use, and more.", "依照遊戲、工作、日常使用等情境，一次切換 Windows 11 設定。"),
        ("About.ProjectLink", "GitHubでプロジェクトを見る", "View the project on GitHub", "在 GitHub 檢視專案"),
        ("About.Version", "バージョン {0}", "Version {0}", "版本 {0}"),
        ("Editor.Title", "モード設定", "Mode settings", "模式設定"),
        ("Editor.Description", "このモードを適用したときの設定を選びます。", "Choose the settings to apply with this mode.", "選擇套用此模式時要使用的設定。"),
        ("Editor.DisplayAc", "画面OFF（電源接続時）", "Turn off display (plugged in)", "關閉螢幕（插入電源）"),
        ("Editor.DisplayBattery", "画面OFF（バッテリー）", "Turn off display (on battery)", "關閉螢幕（使用電池）"),
        ("Editor.SleepAc", "スリープ（電源接続時）", "Sleep (plugged in)", "睡眠（插入電源）"),
        ("Editor.SleepBattery", "スリープ（バッテリー）", "Sleep (on battery)", "睡眠（使用電池）"),
        ("Editor.PowerMode", "電源モード", "Power mode", "電源模式"),
        ("Editor.DefaultMicrophone", "既定のマイク", "Default microphone", "預設麥克風"),
        ("Advanced.Basic", "基本", "General", "基本"),
        ("Advanced.Power", "電源", "Power", "電源"),
        ("Advanced.Display", "ディスプレイ", "Display", "顯示器"),
        ("Advanced.Sound", "音", "Audio", "音效"),
        ("Advanced.Apps", "アプリ", "Apps", "應用程式"),
        ("Advanced.Windows", "ウィンドウ", "Windows", "視窗"),
        ("Advanced.ModeName", "モード名", "Mode name", "模式名稱"),
        ("Advanced.Icon", "アイコン（絵文字）", "Icon (emoji)", "圖示（表情符號）"),
        ("Advanced.Status", "状態", "Status", "狀態"),
        ("Advanced.EnableMode", "このモードを有効にする", "Enable this mode", "啟用此模式"),
        ("Advanced.RestoreDescription", "適用前に現在状態を記録し、このアプリが変更した項目だけを［元に戻す］で可能な範囲で元の状態へ戻します。", "The app records the current state before applying a mode. Restore attempts to return only settings changed by this app.", "套用前會記錄目前狀態；［還原］會盡可能只還原本應用程式變更的項目。"),
        ("Advanced.ChangePowerPlan", "電源プランを変更する", "Change power plan", "變更電源計畫"),
        ("Advanced.PowerPlan", "電源プラン", "Power plan", "電源計畫"),
        ("Advanced.PowerModeAc", "電源モード（電源接続時）", "Power mode (plugged in)", "電源模式（插入電源）"),
        ("Advanced.PowerModeBattery", "電源モード（バッテリー使用時）", "Power mode (on battery)", "電源模式（使用電池）"),
        ("Advanced.DisplayTimeout", "画面を消すまで（電源接続時 / バッテリー使用時）", "Turn off display after (plugged in / battery)", "關閉螢幕時間（插入電源 / 使用電池）"),
        ("Advanced.SleepTimeout", "スリープまで（電源接続時 / バッテリー使用時）", "Sleep after (plugged in / battery)", "睡眠時間（插入電源 / 使用電池）"),
        ("Advanced.SleepPrevention", "一時的なスリープ防止", "Temporary sleep prevention", "暫時防止睡眠"),
        ("Advanced.PowerRestoreDescription", "別の電源プラン内の時間を変更した場合、そのプランの元の値と開始前に使っていたプランを両方元に戻します。", "If a timeout in another power plan is changed, both that plan's original value and the plan active before the mode are restored.", "若變更其他電源計畫中的時間，會同時還原該計畫的原始值及開始前使用的計畫。"),
        ("Advanced.TargetMonitor", "対象モニター", "Target monitor", "目標顯示器"),
        ("Advanced.RefreshRate", "リフレッシュレート（現在の解像度・色深度・向きは維持）", "Refresh rate (keeps resolution, color depth, and orientation)", "重新整理頻率（維持目前解析度、色彩深度與方向）"),
        ("Advanced.TestRefreshRate", "このリフレッシュレートをテスト", "Test this refresh rate", "測試此重新整理頻率"),
        ("Advanced.RefreshRateDescription", "Windowsで利用できる設定か確認した後、一時的に切り替えます。15秒以内に［この設定を使用］を押さなければ自動的に元へ戻ります。モニターや画面構成が変わった場合は、もう一度テストが必要です。", "After Windows confirms the setting is available, it is applied temporarily. If you do not choose “Use this setting” within 15 seconds, it reverts automatically. Test again after changing monitors or the display layout.", "確認 Windows 可使用此設定後會暫時切換。若未在 15 秒內按下［使用此設定］，將自動還原。變更顯示器或畫面配置後需要再次測試。"),
        ("Advanced.OutputVolume", "既定の音声出力 音量（0～100）", "Default audio output volume (0–100)", "預設音訊輸出音量（0～100）"),
        ("Advanced.OutputMute", "既定の音声出力 ミュート", "Default audio output mute", "預設音訊輸出靜音"),
        ("Advanced.MicrophoneVolume", "既定のマイク 音量（0～100）", "Default microphone volume (0–100)", "預設麥克風音量（0～100）"),
        ("Advanced.MicrophoneMute", "既定のマイク ミュート", "Default microphone mute", "預設麥克風靜音"),
        ("Advanced.BlankNoChange", "空欄は変更しない", "Leave blank to keep unchanged", "留空代表不變更"),
        ("Advanced.LaunchTarget", "起動するアプリまたはWebリンク", "App or web link to launch", "要啟動的應用程式或網頁連結"),
        ("Advanced.LaunchArguments", "起動オプション（複数は | で区切る）", "Launch options (separate with |)", "啟動選項（多個請以 | 分隔）"),
        ("Advanced.WorkingDirectory", "起動時に使うフォルダー（任意）", "Launch folder (optional)", "啟動時使用的資料夾（選填）"),
        ("Advanced.Delay", "開始まで（ミリ秒）", "Delay (ms)", "啟動延遲（毫秒）"),
        ("Advanced.Order", "順序", "Order", "順序"),
        ("Advanced.AdditionalInstance", "起動済みでも追加起動", "Launch another instance if already running", "已啟動時仍新增執行個體"),
        ("Advanced.CloseOnRestore", "元に戻すとき終了", "Close when restoring", "還原時關閉"),
        ("Advanced.AddExecutable", "実行ファイルを追加...", "Add executable...", "新增執行檔..."),
        ("Advanced.AddLink", "Webリンクなどを追加", "Add web link or other target", "新增網頁連結等"),
        ("Advanced.CloseTarget", "モード開始時に終了する実行ファイル", "Executable to close when mode starts", "模式開始時要關閉的執行檔"),
        ("Advanced.GracePeriod", "終了を待つ秒数", "Wait to close (sec)", "等待關閉秒數"),
        ("Advanced.AllowForceKill", "強制終了を許可", "Allow force close", "允許強制結束"),
        ("Advanced.RestartOnRestore", "元に戻すとき再起動", "Restart when restoring", "還原時重新啟動"),
        ("Advanced.RestartArguments", "再起動オプション（複数は | で区切る）", "Restart options (separate with |)", "重新啟動選項（多個請以 | 分隔）"),
        ("Advanced.RestartDirectory", "再起動時に使うフォルダー（任意）", "Restart folder (optional)", "重新啟動時使用的資料夾（選填）"),
        ("Advanced.AddCloseTarget", "終了対象を追加...", "Add close target...", "新增關閉目標..."),
        ("Advanced.MonitorTarget", "自動で元に戻すために終了を待つアプリ", "App to wait for before auto-restore", "自動還原前等待結束的應用程式"),
        ("Advanced.AddMonitorTarget", "待つアプリを追加", "Add app to wait for", "新增要等待的應用程式"),
        ("Advanced.CaptureWindows", "現在のウィンドウ配置を保存", "Save current window layout", "儲存目前視窗配置"),
        ("Advanced.WindowDescription", "対象ウィンドウが表示されるまで、0.5秒間隔で最大15秒待ちます。保存時と同じモニターがない場合はメインモニター内へ移動し、一部のウィンドウを移動できなくても残りの処理を続けます。", "The app waits up to 15 seconds in 0.5-second intervals for target windows. If a saved monitor is unavailable, windows are moved onto the primary monitor; other windows continue even if one cannot be moved.", "會每 0.5 秒檢查一次，最長等待目標視窗 15 秒。若沒有儲存時使用的顯示器，會將視窗移至主要顯示器；即使部分視窗無法移動，仍會繼續處理其餘視窗。"),
        ("Diagnostics.ReportTitle", "PC Mode Switcher 診断レポート", "PC Mode Switcher diagnostics report", "PC Mode Switcher 診斷報告"),
        ("Diagnostics.GeneratedUtc", "生成日時（世界標準時）: {0}", "Generated (UTC): {0}", "產生時間（UTC）：{0}"),
        ("Diagnostics.AppVersion", "アプリ: {0}", "App: {0}", "應用程式：{0}"),
        ("Diagnostics.WindowsPowerMode", "Windows 11の電源モード変更: {0}", "Windows 11 power mode changes: {0}", "Windows 11 電源模式變更：{0}"),
        ("Diagnostics.Available", "利用可能", "Available", "可用"),
        ("Diagnostics.Unavailable", "利用不可", "Unavailable", "無法使用"),
        ("Diagnostics.CurrentPowerPlan", "現在の電源プラン: {0}", "Current power plan: {0}", "目前電源計畫：{0}"),
        ("Diagnostics.AvailablePowerPlans", "利用可能な電源プラン:", "Available power plans:", "可用的電源計畫："),
        ("Diagnostics.Active", "[有効]", "[active]", "[啟用]"),
        ("Diagnostics.SleepPreventionAvailable", "モード適用中のスリープ防止: 利用可能", "Sleep prevention while a mode is active: Available", "套用模式時防止睡眠：可用"),
        ("Diagnostics.ConnectedMonitors", "接続中のモニター:", "Connected monitors:", "已連接的顯示器："),
        ("Diagnostics.MonitorLine", "  - {0} {1}x{2} {3}Hz / 候補: {4}", "  - {0} {1}x{2} {3}Hz / available: {4}", "  - {0} {1}x{2} {3}Hz / 可選：{4}"),
        ("Diagnostics.DefaultOutput", "既定の音声出力", "Default audio output", "預設音訊輸出"),
        ("Diagnostics.DefaultMicrophone", "既定のマイク", "Default microphone", "預設麥克風"),
        ("Diagnostics.RestorableNone", "元に戻せるモード設定: なし", "Restorable mode settings: None", "可還原的模式設定：無"),
        ("Diagnostics.RestorableSession", "元に戻せるモード設定: {0} / {1} / 開始 {2}", "Restorable mode settings: {0} / {1} / started {2}", "可還原的模式設定：{0} / {1} / 開始 {2}"),
        ("Diagnostics.LogFolder", "ログフォルダー: {0}", "Log folder: {0}", "記錄資料夾：{0}"),
        ("Diagnostics.SettingsFolder", "設定フォルダー: {0}", "Settings folder: {0}", "設定資料夾：{0}"),
        ("Diagnostics.PowerValue", "{0}: 電源接続時 {1}秒 / バッテリー使用時 {2}秒", "{0}: Plugged in {1} sec / Battery {2} sec", "{0}：插入電源 {1} 秒 / 使用電池 {2} 秒"),
        ("Diagnostics.AudioState", "{0}: ID={1}, 音量={2}, ミュート={3}", "{0}: ID={1}, Volume={2}, Muted={3}", "{0}：ID={1}，音量={2}，靜音={3}"),
        ("Diagnostics.DryRunHeading", "{0} の実行内容（設定は変更しません）", "Actions for {0} (settings will not be changed)", "{0} 的執行內容（不會變更設定）"),
        ("Diagnostics.ChangePlan", "✓ 電源プランを「{0}」へ変更", "✓ Change power plan to “{0}”", "✓ 將電源計畫變更為「{0}」"),
        ("Diagnostics.PlanUnavailable", "⚠ 選択した電源プランは現在利用できません", "⚠ The selected power plan is currently unavailable", "⚠ 目前無法使用選取的電源計畫"),
        ("Diagnostics.PlanNoChange", "– 電源プランは変更しない", "– Do not change the power plan", "– 不變更電源計畫"),
        ("Diagnostics.SleepPreventionDisabled", "– 一時的なスリープ防止は使用しない", "– Temporary sleep prevention is disabled", "– 不使用暫時防止睡眠"),
        ("Diagnostics.SleepPrevention", "✓ 一時的なスリープ防止: {0}", "✓ Temporary sleep prevention: {0}", "✓ 暫時防止睡眠：{0}"),
        ("Diagnostics.RefreshNoChange", "– リフレッシュレートは変更しない", "– Do not change the refresh rate", "– 不變更重新整理頻率"),
        ("Diagnostics.RefreshChange", "{0} {1} を {2}Hzへ変更", "{0} Change {1} to {2}Hz", "{0} 將 {1} 變更為 {2}Hz"),
        ("Diagnostics.AudioNoChange", "– {0}は変更しない", "– Do not change {0}", "– 不變更{0}"),
        ("Diagnostics.AudioChange", "✓ {0}: 音量 {1}% / {2}", "✓ {0}: Volume {1}% / {2}", "✓ {0}：音量 {1}% / {2}"),
        ("Diagnostics.CloseTarget", "✓ {0}へ通常終了を要求", "✓ Request a normal close for {0}", "✓ 要求 {0} 正常結束"),
        ("Diagnostics.CloseMissing", "⚠ 終了対象が見つかりません: {0}", "⚠ Close target not found: {0}", "⚠ 找不到關閉目標：{0}"),
        ("Diagnostics.Launch", "✓ 起動: {0}", "✓ Launch: {0}", "✓ 啟動：{0}"),
        ("Diagnostics.LaunchMissing", "⚠ 起動対象が見つかりません: {0}", "⚠ Launch target not found: {0}", "⚠ 找不到啟動目標：{0}"),
        ("Diagnostics.WindowPlacements", "✓ {0}件のウィンドウ配置を最大15秒待って適用", "✓ Wait up to 15 seconds and apply {0} window placement(s)", "✓ 最多等待 15 秒並套用 {0} 個視窗配置"),
        ("Diagnostics.AutoRestore", "✓ 指定したアプリ{0}件の終了後に自動で元に戻す", "✓ Restore automatically after {0} specified app(s) exit", "✓ 在 {0} 個指定應用程式結束後自動還原"),
        ("Diagnostics.PreventSleep", "PC本体のスリープを防止", "Prevent PC sleep", "防止電腦睡眠"),
        ("Diagnostics.PreventSleepDisplay", "PC本体のスリープと画面OFFを防止", "Prevent PC sleep and display off", "防止電腦睡眠及關閉螢幕"),
        ("Hotkey.Invalid", "{0}のショートカットが正しくありません。", "The shortcut for {0} is invalid.", "{0} 的快速鍵無效。"),
        ("Hotkey.Duplicate", "同じショートカット「{0}」を複数のモードには設定できません。", "The same shortcut “{0}” cannot be assigned to multiple modes.", "無法將同一快速鍵「{0}」指派給多個模式。"),
        ("Hotkey.RegistrationFailed", "{0}のショートカット「{1}」を登録できませんでした。他のアプリやWindowsで使用されていない組み合わせを選んでください。", "The shortcut “{1}” for {0} could not be registered. Choose a combination not used by another app or Windows.", "無法登錄 {0} 的快速鍵「{1}」。請選擇未被其他應用程式或 Windows 使用的組合。"),
        ("Hotkey.RollbackFailed", "{0} 以前のショートカットも元に戻せませんでした。", "{0} The previous shortcuts could not be restored either.", "{0} 先前的快速鍵也無法還原。"),
        ("Diagnostics.Title", "診断", "Diagnostics", "診斷"),
        ("Diagnostics.Copy", "クリップボードへコピー", "Copy to clipboard", "複製到剪貼簿"),
        ("Diagnostics.OpenLogs", "ログフォルダーを開く", "Open log folder", "開啟記錄資料夾"),
        ("Diagnostics.OpenSettings", "設定フォルダーを開く", "Open settings folder", "開啟設定資料夾"),
        ("Diagnostics.SaveReport", "レポートを保存", "Save report", "儲存報告"),
        ("Diagnostics.BackupAll", "すべての設定をバックアップ", "Back up all settings", "備份所有設定"),
        ("DisplayConfirmation.Title", "ディスプレイ設定の確認", "Confirm display settings", "確認顯示設定"),
        ("DisplayConfirmation.Heading", "新しいリフレッシュレートを表示しています", "Displaying the new refresh rate", "正在顯示新的重新整理頻率"),
        ("DisplayConfirmation.Use", "この設定を使用", "Use this setting", "使用此設定"),
        ("Tray.Loading", "モードを読み込んでいます…", "Loading modes...", "正在載入模式…"),
        ("Tray.Show", "表示", "Show", "顯示"),
        ("Tray.OpenSettings", "設定を開く", "Open settings", "開啟設定"),
        ("Tray.Exit", "終了", "Exit", "結束"),
        ("Status.Initial", "モードを選ぶと、設定をまとめて切り替えます。", "Choose a mode to switch its settings together.", "選擇模式即可一次切換相關設定。"),
        ("Status.Checking", "確認中", "Checking", "確認中"),
        ("Status.ModeApplied", "{0}モードに切り替えました", "Switched to {0} mode", "已切換至 {0} 模式"),
        ("Status.ModePartiallyApplied", "{0}モードを一部適用しました", "{0} mode was partially applied", "已部分套用 {0} 模式"),
        ("Status.ModeFailed", "{0}モードを適用できませんでした", "{0} mode could not be applied", "無法套用 {0} 模式"),
        ("Status.ApplyingMode", "{0}モードを適用しています…", "Applying {0} mode...", "正在套用 {0} 模式…"),
        ("Status.SettingsSavedDeleted", "アプリ設定を保存し、追加モードを{0}件削除しました。", "App settings saved and {0} added mode(s) deleted.", "應用程式設定已儲存，並刪除 {0} 個新增模式。"),
        ("Status.ModeCopyName", "{0} のコピー", "Copy of {0}", "{0} 的複本"),
        ("Mode.NewName", "新しいモード", "New mode", "新模式"),
        ("Status.ModeSettingsSaved", "{0}モードの設定を保存しました。", "{0} mode settings saved.", "{0} 模式設定已儲存。"),
        ("Status.RestoredCount", "{0}項目を元に戻しました。", "Restored {0} item(s).", "已還原 {0} 個項目。"),
        ("Status.SkippedCount", "{0}項目をスキップしました。", "Skipped {0} item(s).", "已略過 {0} 個項目。"),
        ("Status.RestoreFailedCount", "{0}項目を元に戻せませんでした。詳細は診断画面で確認できます。", "{0} item(s) could not be restored. See Diagnostics for details.", "有 {0} 個項目無法還原，請在診斷畫面查看詳細資料。"),
        ("Status.MicrophoneOn", "マイク ON", "Microphone ON", "麥克風 開啟"),
        ("Status.MicrophoneOff", "マイク OFF", "Microphone OFF", "麥克風 關閉"),
        ("Status.MicrophoneUnknown", "マイク ?", "Microphone ?", "麥克風 ?"),
        ("Status.MicrophoneOnTip", "Windows側のマイクはONです。クリックするとOFF（ミュート）にします。", "The Windows microphone is on. Click to mute it.", "Windows 麥克風目前開啟。按一下即可靜音。"),
        ("Status.MicrophoneOffTip", "Windows側のマイクはOFF（ミュート）です。クリックするとONにします。", "The Windows microphone is muted. Click to turn it on.", "Windows 麥克風目前已靜音。按一下即可開啟。"),
        ("Status.MicrophoneUnknownTip", "Windows側のマイク状態を確認できません。クリックすると再確認します。", "The Windows microphone state is unknown. Click to check again.", "無法確認 Windows 麥克風狀態。按一下即可重新確認。"),
        ("Status.MicrophoneChanged", "マイクを{0}にしました。", "Microphone set to {0}.", "麥克風已設為{0}。"),
        ("Status.MicrophoneSummary", "マイク：{0}", "Microphone: {0}", "麥克風：{0}"),
        ("Status.MicrophoneNoChangeCurrent", "マイク：変更しない（現在：{0}）", "Microphone: Do not change (current: {0})", "麥克風：不變更（目前：{0}）"),
        ("Status.MicrophoneNoChangeUnknown", "マイク：変更しない（現在状態を確認できません）", "Microphone: Do not change (current state unavailable)", "麥克風：不變更（無法確認目前狀態）"),
        ("Card.AcBattery", "電源接続時 {0} / バッテリー {1}", "Plugged in {0} / Battery {1}", "插入電源 {0} / 電池 {1}"),
        ("Card.AcOnly", "電源接続時 {0}", "Plugged in {0}", "插入電源 {0}"),
        ("Card.Hours", "{0}時間", "{0} hr", "{0} 小時"),
        ("Card.Minutes", "{0}分", "{0} min", "{0} 分鐘"),
        ("Card.Seconds", "{0}秒", "{0} sec", "{0} 秒"),
        ("Card.VolumeMute", "音量 {0}% / {1}", "Volume {0}% / {1}", "音量 {0}% / {1}"),
        ("Card.TrayDisplay", "画面OFF: {0}", "Turn off display: {0}", "關閉螢幕：{0}"),
        ("Card.TraySleep", "スリープ: {0}", "Sleep: {0}", "睡眠：{0}"),
        ("Card.TrayPower", "電源モード: {0}", "Power mode: {0}", "電源模式：{0}"),
        ("Card.TrayMicrophone", "マイク設定（適用時）: {0}", "Microphone (when applied): {0}", "麥克風設定（套用時）：{0}"),
        ("Choice.OneHour", "1時間", "1 hour", "1 小時"),
        ("Choice.TwoHours", "2時間", "2 hours", "2 小時"),
        ("Choice.ThreeHours", "3時間", "3 hours", "3 小時"),
        ("Choice.BestEfficiency", "最も高い電力効率", "Best power efficiency", "最佳電源效率"),
        ("Choice.Balanced", "バランス", "Balanced", "平衡"),
        ("Choice.BestPerformance", "最も高いパフォーマンス", "Best performance", "最佳效能"),
        ("Choice.Disabled", "使用しない", "Disabled", "不使用"),
        ("Choice.PreventSleep", "スリープのみ防止", "Prevent sleep only", "僅防止睡眠"),
        ("Choice.PreventSleepDisplay", "スリープと画面OFFを防止", "Prevent sleep and display off", "防止睡眠及關閉螢幕"),
        ("Choice.Mute", "ミュートする", "Mute", "靜音"),
        ("Choice.Unmute", "ミュートを解除する", "Unmute", "取消靜音"),
        ("Advanced.Verified", "確認済み", "Verified", "已確認"),
        ("Advanced.Unverified", "未確認（テストが必要）", "Not verified (test required)", "未確認（需要測試）"),
        ("Advanced.SavedWindows", "保存済み: {0} ウィンドウ", "Saved: {0} window(s)", "已儲存：{0} 個視窗"),
        ("DisplayConfirmation.Message", "{0} Hz を使用しますか？ {1}秒以内に確認されなければ自動的に元へ戻します。", "Use {0} Hz? It will revert automatically unless confirmed within {1} seconds.", "要使用 {0} Hz 嗎？若未在 {1} 秒內確認，將自動還原。"),
        ("Dialog.DeleteMode", "「{0}」を完全に削除しますか？\n\n［保存］を押すまで削除は確定しません。", "Permanently delete “{0}”?\n\nThe deletion is not finalized until you select Save.", "要永久刪除「{0}」嗎？\n\n按下［儲存］後才會確定刪除。"),
        ("Dialog.DeleteModeTitle", "モードの完全削除", "Delete mode permanently", "永久刪除模式"),
        ("Dialog.HideMode", "このモードをアプリ画面から非表示にしますか？\n\nモード設定は削除されず、［設定］から再表示できます。", "Hide this mode from the app?\n\nIts settings will not be deleted, and it can be shown again in Settings.", "要從應用程式畫面隱藏此模式嗎？\n\n模式設定不會被刪除，可在［設定］中再次顯示。"),
        ("Dialog.ActiveExit", "モードが適用中です。\n\n［はい］元に戻して終了\n［いいえ］終了を取り消す\n［キャンセル］元に戻さず終了", "A mode is active.\n\nYes: Restore and exit\nNo: Cancel exit\nCancel: Exit without restoring", "模式目前正在套用。\n\n［是］還原並結束\n［否］取消結束\n［取消］不還原並結束"),
        ("Dialog.ForceKill", "強制終了すると、対象アプリの未保存データが失われる可能性があります。続行しますか？", "Force closing may discard unsaved data in the target app. Continue?", "強制結束可能會遺失目標應用程式中未儲存的資料。要繼續嗎？"),
        ("Dialog.ForceKillTitle", "強制終了の警告", "Force-close warning", "強制結束警告"),
        ("Dialog.ReviewTitle", "実行内容を確認", "Review actions", "檢視執行內容"),
        ("File.SettingsFilter", "PC Mode Switcher 設定ファイル (*.json)|*.json", "PC Mode Switcher settings (*.json)|*.json", "PC Mode Switcher 設定檔 (*.json)|*.json"),
        ("File.TextFilter", "テキストファイル (*.txt)|*.txt", "Text files (*.txt)|*.txt", "文字檔 (*.txt)|*.txt"),
        ("File.ExecutableFilter", "実行ファイル (*.exe)|*.exe", "Executable files (*.exe)|*.exe", "執行檔 (*.exe)|*.exe"),
        ("File.ExecutableAllFilter", "実行ファイル (*.exe)|*.exe|すべてのファイル (*.*)|*.*", "Executable files (*.exe)|*.exe|All files (*.*)|*.*", "執行檔 (*.exe)|*.exe|所有檔案 (*.*)|*.*"),
        ("Tray.MinimizedHint", "通知領域に格納しました。ダブルクリックで表示、右クリックの［終了］で終了できます。", "Minimized to the notification area. Double-click to show it, or right-click and choose Exit.", "已縮小至通知區域。按兩下可顯示，或按一下右鍵並選擇［結束］。"),
        ("Tray.AppliedSettings", "モードに登録された設定を適用しました。", "Applied the settings registered to this mode.", "已套用此模式中登錄的設定。"),
        ("Dialog.IncompleteSession", "前回適用したモードの設定が、元に戻されていない可能性があります。\n\n［はい］今すぐ元に戻す\n［いいえ］内容を確認\n［キャンセル］元に戻さず閉じる", "Settings from the previously applied mode may not have been restored.\n\nYes: Restore now\nNo: Review details\nCancel: Close without restoring", "上次套用模式的設定可能尚未還原。\n\n［是］立即還原\n［否］查看詳細內容\n［取消］不還原並關閉"),
        ("Dialog.IncompleteSessionTitle", "PC Mode Switcher - 前回の設定を確認", "PC Mode Switcher - Check previous settings", "PC Mode Switcher - 確認上次設定"),
        ("Dialog.IncompleteDetails", "モード: {0}\n開始: {1}\n元に戻せる変更: {2}\n\nメイン画面の［元に戻す］から元の状態へ戻せます。", "Mode: {0}\nStarted: {1}\nRestorable changes: {2}\n\nUse Restore on the main screen to return to the previous state.", "模式：{0}\n開始：{1}\n可還原的變更：{2}\n\n可使用主畫面的［還原］回到原始狀態。"),
        ("Dialog.PreviousModeSettings", "前回のモード設定", "Previous mode settings", "上次的模式設定")
    ];

    private static readonly (string Ja, string En, string Zh)[] Messages =
    [
        ("予期しない問題が発生しました。操作を中止しました。", "An unexpected problem occurred. The operation was stopped.", "發生未預期的問題，操作已停止。"),
        ("確認中", "Checking", "確認中"),
        ("モードを選ぶと、設定をまとめて切り替えます。", "Choose a mode to switch its settings together.", "選擇模式即可一次切換相關設定。"),
        ("変更しない", "Do not change", "不變更"),
        ("設定エラー", "Settings error", "設定錯誤"),
        ("ミュート変更なし", "Do not change mute", "不變更靜音"),
        ("なし", "Never", "永不"),
        ("利用不可", "Unavailable", "無法使用"),
        ("未登録の設定", "Unregistered settings", "未登錄的設定"),
        ("確認できません", "Cannot determine", "無法確認"),
        ("バージョン不明", "Version unknown", "版本不明"),
        ("初期設定で開始しました。", "Started with default settings.", "已使用初始設定啟動。"),
        ("閉じるボタンの動作が正しくありません。", "The close-button behavior is invalid.", "關閉按鈕動作無效。"),
        ("標準モードは完全削除できません。非表示または無効にしてください。", "Built-in modes cannot be deleted permanently. Hide or disable them instead.", "內建模式無法永久刪除，請改為隱藏或停用。"),
        ("削除するモードが見つかりません。", "The mode to delete was not found.", "找不到要刪除的模式。"),
        ("有効なモードを1個以上選んでください。", "Select at least one enabled mode.", "請至少選擇一個啟用的模式。"),
        ("アプリ画面に表示するモードは1〜5個で選んでください。", "Choose 1–5 modes to show in the app.", "請選擇 1～5 個要顯示於應用程式的模式。"),
        ("アプリ設定を保存しました。", "App settings saved.", "應用程式設定已儲存。"),
        ("既定のマイクの状態を確認できないため、切り替えませんでした。", "The default microphone state could not be determined, so it was not changed.", "無法確認預設麥克風狀態，因此未進行切換。"),
        ("現在の状態は再確認できませんでした。", "The current state could not be checked again.", "無法再次確認目前狀態。"),
        ("モード適用前の状態へ戻しています…", "Restoring the state from before the mode was applied...", "正在還原套用模式前的狀態…"),
        ("複製元のモードが見つかりません。", "The source mode was not found.", "找不到複製來源模式。"),
        ("非表示にするモードが画面に見つかりません。", "The mode to hide was not found on the screen.", "畫面上找不到要隱藏的模式。"),
        ("最後の表示モードは非表示にできません。", "The last visible mode cannot be hidden.", "無法隱藏最後一個顯示中的模式。"),
        ("モードをアプリ画面から非表示にしました。設定から再表示できます。", "The mode was hidden from the app. You can show it again in Settings.", "已從應用程式畫面隱藏此模式，可在設定中再次顯示。"),
        ("並べ替えるモードが画面に見つかりません。", "The mode to reorder was not found on the screen.", "畫面上找不到要重新排序的模式。"),
        ("モードの表示順を変更しました。", "Mode display order changed.", "模式顯示順序已變更。"),
        ("モード設定を読み込みました。", "Mode settings imported.", "模式設定已匯入。"),
        ("モード設定を書き出しました。", "Mode settings exported.", "模式設定已匯出。"),
        ("モード設定を書き出せませんでした。", "Mode settings could not be exported.", "無法匯出模式設定。"),
        ("モード設定を読み込めませんでした。", "Mode settings could not be imported.", "無法匯入模式設定。"),
        ("保存済みのモード設定を読み込めませんでした。", "Saved mode settings could not be loaded.", "無法載入已儲存的模式設定。"),
        ("設定ファイルはこのアプリより新しい形式です。上書きしません。", "The settings file uses a newer format and will not be overwritten.", "設定檔格式比本應用程式新，因此不會覆寫。"),
        ("読み込むファイルの形式が正しくありません。", "The selected file format is invalid.", "所選檔案格式無效。"),
        ("モード設定が正しくないため保存しませんでした。", "The mode settings are invalid and were not saved.", "模式設定無效，因此未儲存。"),
        ("モード設定を保存しました。", "Mode settings saved.", "模式設定已儲存。"),
        ("モード設定を保存できませんでした。", "Mode settings could not be saved.", "無法儲存模式設定。"),
        ("バックアップを作成できませんでした。", "The backup could not be created.", "無法建立備份。"),
        ("マイク設定が正しくありません。", "The microphone setting is invalid.", "麥克風設定無效。"),
        ("マイクのミュート状態は変更しませんでした。", "The microphone mute state was not changed.", "未變更麥克風靜音狀態。"),
        ("電源モードが選択されていません。", "No power mode is selected.", "未選擇電源模式。"),
        ("選択した電源モードはこのPCで利用できません。", "The selected power mode is unavailable on this PC.", "此電腦無法使用選取的電源模式。"),
        ("電源モードを切り替えました。", "Power mode changed.", "電源模式已切換。"),
        ("電源モードの切り替えを確認できませんでした。", "The power mode change could not be verified.", "無法確認電源模式是否已切換。"),
        ("現在のWindows電源設定を確認できませんでした。", "The current Windows power settings could not be determined.", "無法確認目前的 Windows 電源設定。"),
        ("利用可能な電源プランがありません。", "No power plans are available.", "沒有可用的電源計畫。"),
        ("元に戻すための情報がありません。", "No restore information is available.", "沒有可用的還原資訊。"),
        ("変更しない設定です。", "This setting is unchanged.", "此設定不會變更。"),
        ("Windows 11でのみ利用できます。", "This feature is available only on Windows 11.", "此功能僅能在 Windows 11 使用。"),
        ("このWindowsでは電源モードを変更できません。", "Power mode cannot be changed on this version of Windows.", "此版本的 Windows 無法變更電源模式。"),
        ("Windowsへ電源モードを要求しました。", "Requested the power mode from Windows.", "已向 Windows 要求變更電源模式。"),
        ("電源モードを要求できませんでした。", "The power mode could not be requested.", "無法要求變更電源模式。"),
        ("使用しない設定です。", "This setting is disabled.", "此設定已停用。"),
        ("自動スリープを一時的に防止しました。", "Automatic sleep is temporarily prevented.", "已暫時防止自動睡眠。"),
        ("一時的なスリープ防止を解除しました。", "Temporary sleep prevention ended.", "已解除暫時防止睡眠。"),
        ("登録項目がありません。", "No items are registered.", "沒有已登錄的項目。"),
        ("実行ファイルが見つかりません。", "The executable was not found.", "找不到執行檔。"),
        ("プロセスを開始できませんでした。", "The process could not be started.", "無法啟動處理程序。"),
        ("操作をキャンセルしました。", "The operation was canceled.", "操作已取消。"),
        ("現在状態を記録できないため変更しません。", "The current state could not be recorded, so no change was made.", "無法記錄目前狀態，因此未進行變更。"),
        ("適用中に予期しない問題が発生しました。", "An unexpected problem occurred while applying the mode.", "套用模式時發生未預期的問題。"),
        ("元に戻す途中で予期しない問題が発生しました。", "An unexpected problem occurred while restoring.", "還原時發生未預期的問題。"),
        ("元に戻すモードはありません。", "There is no mode to restore.", "沒有需要還原的模式。"),
        ("すでに元に戻しています。", "Restore is already in progress.", "已在進行還原。"),
        ("スタートアップ設定を開けませんでした。", "Startup settings could not be opened.", "無法開啟啟動設定。"),
        ("アプリの実行ファイルを特定できないため、スタートアップへ登録できませんでした。", "The app executable could not be identified, so startup registration failed.", "無法識別應用程式執行檔，因此無法登錄為啟動程式。"),
        ("スタートアップ設定を変更できませんでした。", "Startup settings could not be changed.", "無法變更啟動設定。"),
        ("すべての設定を選択してください。", "Select all settings.", "請選擇所有設定。"),
        ("モニターとリフレッシュレートを選択してください。", "Select a monitor and refresh rate.", "請選擇顯示器及重新整理頻率。"),
        ("モード名を入力してください。", "Enter a mode name.", "請輸入模式名稱。"),
        ("電源プランを選択してください。", "Select a power plan.", "請選擇電源計畫。"),
        ("音量は空欄（変更しない）または0～100で入力してください。", "Leave volume blank (unchanged) or enter a value from 0 to 100.", "音量請留空（不變更）或輸入 0～100。"),
        ("Ctrl、Alt、Shift、Winのいずれかを同時に押してください。", "Press a key together with Ctrl, Alt, Shift, or Win.", "請同時按下 Ctrl、Alt、Shift 或 Win 與另一按鍵。"),
        ("アプリ画面に表示できるモードは最大5個です。", "Up to five modes can be shown in the app.", "應用程式最多可顯示五個模式。"),
        ("表示するモードを1個以上選んでください。", "Select at least one mode to show.", "請至少選擇一個要顯示的模式。"),
        ("表示言語が正しくありません。", "The display language is invalid.", "顯示語言無效。")
    ];

    internal static Dictionary<string, string> Create(int language)
    {
        var values = Ui.ToDictionary(
            item => item.Key,
            item => language switch { 1 => item.En, 2 => item.Zh, _ => item.Ja },
            StringComparer.Ordinal);
        foreach (var message in Messages)
            values["Message." + message.Ja] =
                language switch { 1 => message.En, 2 => message.Zh, _ => message.Ja };
        AddServiceMessages(values, language);
        return values;
    }
}
